name: Continuous Integration

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Linter
        run: npm run lint

      - name: Run E2E Testing
        uses: cypress-io/github-action@v6
        with:
         install: false
          start: npm run dev
          wait-on: 'http://localhost:5173'